name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Check build output
        run: |
          echo "Build output:"
          ls -la dist/
          ls -la dist/bin/
          echo "Package.json version:"
          cat package.json | grep version

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## 🚀 What's New in ${{ github.ref_name }}
            
            ### ✨ New Features
            - Interactive folder browser starting from root directory
            - Command line arguments support (--help, --version, input-path)
            - Graceful exit handling with file cleanup options
            
            ### 🐛 Bug Fixes
            - Fixed video conversion codec and format mismatch issues
            - Fixed prompt navigation when going back to previous steps
            - Improved Jest configuration for CI/CD pipeline
            
            ### 🔧 Improvements
            - Enhanced CLI user experience with better navigation
            - Improved error handling and user feedback
            - Added comprehensive documentation updates
            
            ## 📦 Installation
            ```bash
            npm install -g media-to-web
            # or
            npx media-to-web
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
